framework:
    mailer:
       transport: 'sendgrid://default'
        # For more configuration options, refer to the Symfony documentation:
        # https://symfony.com/doc/current/mailer.html#transport-configuration
